#!/bin/sh
python generate_matriz.py $1 $2
mat1="matrix$1_$2"
mat2="matrix$1_$2_2"
mat3="matrix$1_$2_result"
file1="matrixs/$mat1"
file2="matrixs/$mat2"
file3="matrixs/$mat3"
echo "$file1 $file2"
./a $file1 $file2 > r
cmp r $file3
./b $file1 $file2 > r
cmp r $file3


